version: '3'
services:
  tomcat:
    image: tomcat
    restart: always
    container_name: tomcat
    build:
      context: ./src
    ports:
      - '80:8080'
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql-db:/var/lib/mysql