version: '3'
services:
  tomcat:
    image: tomcat
    restart: always
    container_name: tomcat
    build:
      context: ./src
    volumes:
      - ./src/ip-lab:/usr/local/tomcat/webapps/ip-lab
    ports:
      - '80:8080'
